version: '2.0'
services:
  ruby:
    restart: always
    image: ruby:2.4
    env_file: ./ruby/config/.env
    container_name: ruby
    volumes:
      - "$PWD"/ruby:/usr/src/app
  selenium:
    restart: always
    image: selenium/standalone-firefox-debug:3.0.1
    env_file:
    container_name: selenium
    ports:
      - "15900:5900"
    volume_from:
      - ruby
  jenkins:
    restart: always
    image: jenkins:2.32.1
    env_file:
    container_name: jenkins
    ports:
      - "18080:8080"
    volumes:
      - "$PWD"/jenkins:/var/jenkins_home
    links:
      - ruby
