version: '2.0'
services:

  # for e2e selenium
  selenium:
    image: selenium/standalone-firefox-debug:3.0.1
    container_name: selenium
    restart: always
    ports:
      - 5900:5900 #VNC
    expose:
      - 4444 #selenium
    volumes:
      - ./ruby/download:/home/seluser # for download file

  # for scripts
  ruby:
    build:
      context: ./ruby
      dockerfile: Dockerfile
      args:
        - password=${DOCKER_PASSWORD}
    container_name: ruby
    restart: always
    depends_on:
      - selenium
    volumes:
      - ./ruby:/usr/src/app
    environment:
      - SELENIUM_HOST=${SELENIUM_HOST}
      - SELENIUM_PORT=${SELENIUM_PORT}

  # for execute tool
  jenkins:
    build: ./jenkins/
    container_name: jenkins
    restart: always
    ports:
      - "18080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
    volumes_from:
      - ruby
    environment:
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
