version: '2.0'
services:

  # for e2e selenium
  selenium:
    image: selenium/standalone-firefox-debug:3.0.1
    container_name: selenium
    restart: always
    ports:
      - 15900:5900 #VNC
      - 4444:4444 #VNC
    expose:
      - 4444 #selenium
    volumes:
      - ./ruby/download:/home/seluser # for download file

  # for scripts
  ruby:
    image: ruby:2.4
    container_name: ruby
    restart: always
    links:
      - selenium
    volumes:
      - ./ruby:/usr/src/app
    command: tail -f /dev/null
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444

  # for execute tool
  jenkins:
    image: jenkins:2.32.1
    container_name: jenkins
    restart: always
    ports:
      - "18080:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
    volumes_from:
      - ruby
